# Generated by Django 5.2.7 on 2026-06-04 09:34

from django.db import migrations, models


def seed_instrument_mappings(apps, schema_editor):
    InstrumentMapping = apps.get_model("pricing", "InstrumentMapping")
    from apps.pricing.services.instrument_service import load_seed_json

    for isin, ticker in load_seed_json().items():
        InstrumentMapping.objects.update_or_create(
            isin=isin,
            defaults={"yahoo_ticker": ticker, "source": "seed_json"},
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentMapping',
            fields=[
                ('isin', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='ISIN')),
                ('yahoo_ticker', models.CharField(max_length=32, verbose_name='Yahoo-ticker')),
                ('mic', models.CharField(blank=True, default='', max_length=12, verbose_name='MIC')),
                ('asset_type', models.CharField(blank=True, default='', help_text='stock, etf, fund — optioneel uit OpenFIGI', max_length=20, verbose_name='assettype-hint')),
                ('security_type', models.CharField(blank=True, default='', max_length=64, verbose_name='OpenFIGI type')),
                ('source', models.CharField(choices=[('seed_json', 'Seed (JSON)'), ('openfigi', 'OpenFIGI'), ('manual', 'Handmatig')], default='seed_json', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'instrumentmapping',
                'verbose_name_plural': 'instrumentmappings',
                'ordering': ['isin'],
            },
        ),
        migrations.RunPython(seed_instrument_mappings, migrations.RunPython.noop),
    ]
