# Generated by Django 5.2.7 on 2026-06-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxYearParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('heffingsvrij_vermogen', models.DecimalField(decimal_places=2, max_digits=14)),
                ('rendement_banktegoeden', models.DecimalField(decimal_places=6, help_text='PB, bijv. 0.0128', max_digits=8)),
                ('rendement_overige_bezittingen', models.DecimalField(decimal_places=6, help_text='PO, bijv. 0.06', max_digits=8)),
                ('rendement_schulden', models.DecimalField(decimal_places=6, help_text='PS, bijv. 0.027', max_digits=8)),
                ('schuldendrempel', models.DecimalField(decimal_places=2, help_text='SD', max_digits=14)),
                ('tarief_box3', models.DecimalField(decimal_places=6, help_text='T, bijv. 0.36', max_digits=8)),
                ('banktegoeden_definitief', models.BooleanField(default=False)),
                ('schulden_definitief', models.BooleanField(default=False)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'belastingjaar-parameter',
                'verbose_name_plural': 'belastingjaar-parameters',
                'ordering': ['-year'],
            },
        ),
    ]
