# Generated by Django 5.2.7 on 2026-06-01 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0002_seed_2026_parameters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Box3RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_year', models.PositiveIntegerField(verbose_name='belastingjaar')),
                ('label', models.CharField(max_length=120)),
                ('property_type', models.CharField(choices=[('second_home_nl', '2e woning NL'), ('second_home_abroad', '2e woning buitenland'), ('rental_nl', 'Verhuurd NL'), ('rental_abroad', 'Verhuurd buitenland'), ('other', 'Overig onroerend')], default='second_home_nl', max_length=32)),
                ('value_eur', models.DecimalField(decimal_places=2, help_text='WOZ of WEV op peildatum', max_digits=14)),
                ('is_abroad', models.BooleanField(default=False)),
                ('annual_rent_eur', models.DecimalField(decimal_places=2, default=0, help_text='Jaarhuur (voor leegwaarderatio indicatie).', max_digits=14)),
                ('vacancy_ratio', models.DecimalField(blank=True, decimal_places=4, help_text='Leegwaarderatio 0–1 voor verhuur.', max_digits=5, null=True)),
                ('rental_income_ytd_eur', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('eigen_gebruik_days', models.PositiveIntegerField(default=0)),
                ('verhuur_days', models.PositiveIntegerField(default=0)),
                ('verbouw_days', models.PositiveIntegerField(default=0)),
                ('bijtelling_method', models.CharField(blank=True, choices=[('huurwaarde', 'Economische huurwaarde'), ('woz_vast', 'Vast percentage WOZ')], default='', max_length=16)),
                ('economic_rent_yearly_eur', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('woz_previous_year_eur', models.DecimalField(decimal_places=2, default=0, help_text='WOZ vorig jaar (methode B bijtelling).', max_digits=14)),
                ('bijtelling_rate', models.DecimalField(decimal_places=4, default=0, help_text='Leeg = standaard 5,06% voor 2026.', max_digits=6)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box3_real_estate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'box 3-vastgoed',
                'verbose_name_plural': 'box 3-vastgoed',
                'ordering': ['-tax_year', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Box3Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_year', models.PositiveIntegerField(verbose_name='belastingjaar')),
                ('label', models.CharField(max_length=120)),
                ('debt_type', models.CharField(choices=[('consumer', 'Consumptief'), ('investment', 'Beleggingsfinanciering'), ('mortgage_second_home', 'Hypotheek 2e woning'), ('negative_balance', 'Negatief banksaldo'), ('other', 'Overig')], default='other', max_length=32)),
                ('outstanding_eur', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interest_paid_ytd_eur', models.DecimalField(decimal_places=2, default=0, help_text='Betaalde rente dit jaar (werkelijk rendement).', max_digits=14)),
                ('creditor', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box3_debts', to=settings.AUTH_USER_MODEL)),
                ('linked_real_estate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debts', to='tax.box3realestate')),
            ],
            options={
                'verbose_name': 'box 3-schuld',
                'verbose_name_plural': 'box 3-schulden',
                'ordering': ['-tax_year', 'label'],
            },
        ),
    ]
