# Generated by Django 5.2.7 on 2026-06-01 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0003_box3realestate_box3debt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Box3BankBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_year', models.PositiveIntegerField(verbose_name='belastingjaar')),
                ('label', models.CharField(max_length=120)),
                ('account_type', models.CharField(choices=[('savings', 'Spaarrekening'), ('checking', 'Betaalrekening'), ('deposit', 'Depositorekening'), ('other', 'Overig banktegoed')], default='savings', max_length=32)),
                ('balance_eur', models.DecimalField(decimal_places=2, help_text='Saldo op peildatum (1 januari).', max_digits=14)),
                ('institution', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box3_bank_balances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'box 3-banktegoed',
                'verbose_name_plural': 'box 3-banktegoeden',
                'ordering': ['-tax_year', 'label'],
            },
        ),
    ]
