# Generated by Django 5.2.7 on 2026-06-01 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32, verbose_name='symbool')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='naam')),
                ('asset_type', models.CharField(choices=[('crypto', 'Crypto'), ('stock', 'Aandeel'), ('etf', 'ETF'), ('fund', 'Fonds'), ('metal', 'Edelmetaal'), ('cash', 'Spaargeld'), ('other', 'Overig')], default='other', max_length=20)),
                ('category', models.CharField(choices=[('banktegoed', 'Banktegoed'), ('belegging', 'Belegging'), ('edelmetaal', 'Edelmetaal'), ('schuld', 'Schuld'), ('overig', 'Overig')], default='belegging', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'asset',
                'verbose_name_plural': 'assets',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Hoofdportefeuille', max_length=120, verbose_name='naam')),
                ('is_default', models.BooleanField(default=True, verbose_name='standaard')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'portefeuille',
                'verbose_name_plural': 'portefeuilles',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=12, default=0, max_digits=24, verbose_name='aantal')),
                ('average_cost_eur', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='gemiddelde kostprijs (EUR)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='portfolio.asset')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='portfolio.portfolio')),
            ],
            options={
                'verbose_name': 'positie',
                'verbose_name_plural': 'posities',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('buy', 'Aankoop'), ('sell', 'Verkoop'), ('dividend', 'Dividend'), ('deposit', 'Storting'), ('withdrawal', 'Opname'), ('fee', 'Kosten'), ('other', 'Overig')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=12, max_digits=24)),
                ('price_eur', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='prijs per eenheid (EUR)')),
                ('fee_eur', models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='kosten (EUR)')),
                ('total_eur', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='totaal (EUR)')),
                ('occurred_at', models.DateTimeField(verbose_name='datum')),
                ('external_id', models.CharField(blank=True, default='', max_length=128, verbose_name='extern ID')),
                ('transaction_hash', models.CharField(db_index=True, max_length=64)),
                ('source_platform', models.CharField(blank=True, default='', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolio.asset')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolio.portfolio')),
            ],
            options={
                'verbose_name': 'transactie',
                'verbose_name_plural': 'transacties',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('user', 'symbol'), name='unique_asset_symbol_per_user'),
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='unique_default_portfolio_per_user'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('portfolio', 'asset'), name='unique_position_per_portfolio_asset'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('portfolio', 'transaction_hash'), name='unique_transaction_hash_per_portfolio'),
        ),
    ]
