# Generated by Django 5.2.7 on 2026-05-25 22:25

import apps.accounts.managers
import apps.accounts.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mailadres')),
                ('first_name', models.CharField(max_length=150, verbose_name='voornaam')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='achternaam')),
                ('email_verified', models.BooleanField(default=False, verbose_name='e-mail geverifieerd')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_tier', models.CharField(choices=[('free', 'Gratis'), ('premium', 'Premium')], default='free', max_length=20)),
                ('active_tax_year', models.PositiveIntegerField(default=apps.accounts.models.default_active_tax_year, help_text='Belastingjaar waarvoor fiscale berekeningen worden getoond.', verbose_name='actief belastingjaar')),
                ('has_fiscal_partner', models.BooleanField(default=False, help_text='Verdubbelt het heffingsvrije vermogen in box 3-berekeningen.', verbose_name='fiscaal partner')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'gebruiker',
                'verbose_name_plural': 'gebruikers',
                'ordering': ['email'],
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
    ]
