# Generated by Django 5.2.7 on 2026-05-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_twofa_and_password_reset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twofactorbackupcode',
            name='user',
        ),
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='used_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_2fa_enabled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='totp_confirmed_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='totp_secret_encrypted',
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='auth_0_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Auth0 user ID'),
        ),
        migrations.DeleteModel(
            name='MfaLoginChallenge',
        ),
        migrations.DeleteModel(
            name='TwoFactorBackupCode',
        ),
    ]
