# Generated by Django 5.2.7 on 2026-06-01 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('bitvavo', 'Bitvavo'), ('degiro', 'DEGIRO'), ('manual', 'Handmatig')], max_length=32)),
                ('connection_method', models.CharField(choices=[('api', 'API'), ('csv', 'CSV'), ('manual', 'Handmatig')], default='api', max_length=16)),
                ('label', models.CharField(blank=True, default='', max_length=120, verbose_name='label')),
                ('api_key_encrypted', models.TextField(blank=True, default='')),
                ('api_secret_encrypted', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'In wachtrij'), ('running', 'Bezig'), ('success', 'Geslaagd'), ('error', 'Fout')], default='pending', max_length=16)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_connections', to='portfolio.portfolio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'platformkoppeling',
                'verbose_name_plural': 'platformkoppelingen',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'In wachtrij'), ('running', 'Bezig'), ('success', 'Geslaagd'), ('error', 'Fout')], default='pending', max_length=16)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('positions_synced', models.PositiveIntegerField(default=0)),
                ('transactions_synced', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='integrations.platformconnection')),
            ],
            options={
                'verbose_name': 'sync-taak',
                'verbose_name_plural': 'sync-taken',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='platformconnection',
            constraint=models.UniqueConstraint(fields=('user', 'platform', 'label'), name='unique_platform_connection_label'),
        ),
    ]
