# Generated by Django 5.2.7 on 2026-06-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconnection',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Voorbeelddata zonder echte broker-API. Alleen in development.', verbose_name='demo-koppeling'),
        ),
    ]
