# Generated by Django 5.2.7 on 2026-06-02 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_platformconnection_is_demo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvImportDiagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=32)),
                ('schema_version', models.CharField(blank=True, default='', max_length=64)),
                ('event', models.CharField(choices=[('preview', 'Preview'), ('import', 'Import'), ('rejected', 'Afgewezen')], max_length=16)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=64)),
                ('file_headers', models.JSONField(default=list)),
                ('missing_canonical', models.JSONField(default=list)),
                ('unmapped_headers', models.JSONField(default=list)),
                ('unknown_descriptions', models.JSONField(default=list)),
                ('schema_warnings', models.JSONField(default=list)),
                ('suggested_aliases', models.JSONField(default=list)),
                ('rows_in_file', models.PositiveIntegerField(default=0)),
                ('rows_recognized', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_import_diagnostics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CSV-import diagnostiek',
                'verbose_name_plural': 'CSV-import diagnostiek',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['platform', 'created_at'], name='integration_platfor_3f84df_idx'), models.Index(fields=['event', 'created_at'], name='integration_event_2db694_idx')],
            },
        ),
    ]
