# Generated by Django 5.2.7 on 2026-06-07 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_csv_import_diagnostic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('bitvavo', 'Bitvavo'), ('degiro', 'DEGIRO'), ('manual', 'Handmatig')], max_length=32)),
                ('connection_method', models.CharField(choices=[('api', 'API'), ('csv', 'CSV'), ('manual', 'Handmatig')], default='csv', max_length=16)),
                ('source_label', models.CharField(blank=True, default='', max_length=160)),
                ('source_filename', models.CharField(blank=True, default='', max_length=255)),
                ('ai_used', models.BooleanField(default=False)),
                ('column_mapping', models.JSONField(blank=True, default=dict)),
                ('rows_in_file', models.PositiveIntegerField(default=0)),
                ('rows_recognized', models.PositiveIntegerField(default=0)),
                ('transactions_imported', models.PositiveIntegerField(default=0)),
                ('transactions_skipped', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='integrations.platformconnection')),
                ('sync_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to='integrations.syncjob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'platform-import',
                'verbose_name_plural': 'platform-imports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['connection', 'created_at'], name='integration_connect_ec8da4_idx'), models.Index(fields=['platform', 'created_at'], name='integration_platfor_2c3faf_idx')],
            },
        ),
    ]
