# Generated by Django 5.2.7 on 2026-06-07 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_platformimportbatch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedCsvColumnAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('bitvavo', 'Bitvavo'), ('degiro', 'DEGIRO'), ('manual', 'Handmatig')], max_length=32)),
                ('canonical', models.CharField(max_length=32)),
                ('header_normalized', models.CharField(max_length=128)),
                ('header_example', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'In afwachting'), ('verified', 'Geverifieerd'), ('disabled', 'Uitgeschakeld')], default='pending', max_length=16)),
                ('confirmation_count', models.PositiveIntegerField(default=0)),
                ('conflict_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_column_aliases_first', to='integrations.platformimportbatch')),
            ],
            options={
                'verbose_name': 'CSV-kolomalias (gedeeld)',
                'verbose_name_plural': 'CSV-kolomaliases (gedeeld)',
            },
        ),
        migrations.CreateModel(
            name='SharedCsvColumnAliasConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='integrations.sharedcsvcolumnalias')),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_alias_confirmations', to='integrations.platformimportbatch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_csv_alias_confirmations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CSV-kolomalias bevestiging',
                'verbose_name_plural': 'CSV-kolomalias bevestigingen',
            },
        ),
        migrations.CreateModel(
            name='UserCsvColumnAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('bitvavo', 'Bitvavo'), ('degiro', 'DEGIRO'), ('manual', 'Handmatig')], max_length=32)),
                ('canonical', models.CharField(max_length=32)),
                ('header_normalized', models.CharField(max_length=128)),
                ('header_example', models.CharField(blank=True, default='', max_length=255)),
                ('use_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_column_aliases_created', to='integrations.platformimportbatch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_column_aliases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CSV-kolomalias (user)',
                'verbose_name_plural': 'CSV-kolomaliases (user)',
            },
        ),
        migrations.AddIndex(
            model_name='sharedcsvcolumnalias',
            index=models.Index(fields=['platform', 'status'], name='integration_platfor_f8f78a_idx'),
        ),
        migrations.AddConstraint(
            model_name='sharedcsvcolumnalias',
            constraint=models.UniqueConstraint(fields=('platform', 'header_normalized'), name='unique_shared_csv_column_alias'),
        ),
        migrations.AddConstraint(
            model_name='sharedcsvcolumnaliasconfirmation',
            constraint=models.UniqueConstraint(fields=('alias', 'user'), name='unique_shared_csv_alias_confirmation'),
        ),
        migrations.AddIndex(
            model_name='usercsvcolumnalias',
            index=models.Index(fields=['user', 'platform'], name='integration_user_id_179c85_idx'),
        ),
        migrations.AddIndex(
            model_name='usercsvcolumnalias',
            index=models.Index(fields=['platform', 'header_normalized'], name='integration_platfor_6f4c5f_idx'),
        ),
        migrations.AddConstraint(
            model_name='usercsvcolumnalias',
            constraint=models.UniqueConstraint(fields=('user', 'platform', 'header_normalized'), name='unique_user_csv_column_alias'),
        ),
    ]
