# Generated by Django 5.2.7 on 2026-06-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_platformconnection_api_passphrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformconnection',
            name='platform',
            field=models.CharField(choices=[('bitvavo', 'Bitvavo'), ('bybit', 'Bybit'), ('okx', 'OKX'), ('degiro', 'DEGIRO'), ('trading212', 'Trading 212'), ('trade_republic', 'Trade Republic'), ('manual', 'Handmatig')], max_length=32),
        ),
        migrations.AlterField(
            model_name='platformimportbatch',
            name='platform',
            field=models.CharField(choices=[('bitvavo', 'Bitvavo'), ('bybit', 'Bybit'), ('okx', 'OKX'), ('degiro', 'DEGIRO'), ('trading212', 'Trading 212'), ('trade_republic', 'Trade Republic'), ('manual', 'Handmatig')], max_length=32),
        ),
        migrations.AlterField(
            model_name='sharedcsvcolumnalias',
            name='platform',
            field=models.CharField(choices=[('bitvavo', 'Bitvavo'), ('bybit', 'Bybit'), ('okx', 'OKX'), ('degiro', 'DEGIRO'), ('trading212', 'Trading 212'), ('trade_republic', 'Trade Republic'), ('manual', 'Handmatig')], max_length=32),
        ),
        migrations.AlterField(
            model_name='usercsvcolumnalias',
            name='platform',
            field=models.CharField(choices=[('bitvavo', 'Bitvavo'), ('bybit', 'Bybit'), ('okx', 'OKX'), ('degiro', 'DEGIRO'), ('trading212', 'Trading 212'), ('trade_republic', 'Trade Republic'), ('manual', 'Handmatig')], max_length=32),
        ),
    ]
