# Generated by Django 5.2.7 on 2026-06-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_add_okx_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformconnection',
            name='okx_domain',
            field=models.CharField(choices=[('okx.com', 'okx.com (Global - www.okx.com)'), ('eea.okx.com', 'eea.okx.com (EU/NL - my.okx.com)'), ('us.okx.com', 'us.okx.com (US/AU - app.okx.com)')], default='okx.com', help_text='OKX API domein (okx.com of okx.nl)', max_length=16),
        ),
    ]
